# Generated by Django 3.2 on 2021-04-30 05:41

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("institution", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "referralCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("yos_designation", models.CharField(max_length=100)),
                (
                    "mobile",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mobile",
                                message="Enter a valid mobile number",
                                regex="^(\\+\\d{1,3}[- ]?)?\\d{10}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
