# Generated by Django 3.2 on 2021-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="event",
            field=models.CharField(
                choices=[
                    ("Webinar", "Webinar"),
                    ("Designique", "Designique"),
                    ("Both", "Both"),
                ],
                default="Webinar",
                max_length=15,
            ),
        ),
    ]
