# Generated by Django 3.2 on 2021-05-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_participant_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="firstName",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="lastName",
        ),
    ]
